version: '3.8'

services:
  backend:
    build: ./SCClouds-Test
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build: ./Front-end
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: unless-stopped
