# Usa uma imagem com Gradle pré-instalado
FROM gradle:8.5-jdk21 AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Executa o build da aplicação
RUN gradle build --no-daemon

# Segunda etapa: Apenas para rodar o app
FROM openjdk:21-jdk-slim

WORKDIR /app

# Copia apenas o JAR gerado
COPY --from=build /app/build/libs/*.jar app.jar

# Expõe a porta 8081
EXPOSE 8081

# Comando para rodar a aplicação
CMD ["java", "-jar", "app.jar"]




